# Generated by Django 5.2.8 on 2026-05-02 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_agendamento', models.BigIntegerField()),
                ('data', models.DateTimeField()),
                ('lida', models.BooleanField(default=False)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('id_paciente', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacao',
                'ordering': ['data'],
                'indexes': [models.Index(fields=['id_agendamento'], name='notificacao_id_agen_7b8ca9_idx'), models.Index(fields=['data'], name='notificacao_data_f92bdd_idx'), models.Index(fields=['lida'], name='notificacao_lida_1f8f83_idx')],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(blank=True, max_length=255)),
                ('cadastro_confirmado', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('ROLE_USER', 'User'), ('ROLE_ADMIN', 'Admin')], default='ROLE_USER', max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('modo_google', models.BooleanField(default=False)),
                ('timeout_seconds', models.BigIntegerField(blank=True, default=10000)),
                ('ativar_notificacoes_consultas', models.BooleanField(default=True)),
                ('ativar_notificacoes_graacc', models.BooleanField(default=True)),
                ('id_paciente', models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='restfull.paciente')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=255)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='restfull.usuario')),
            ],
            options={
                'verbose_name': 'PushSubscription',
                'verbose_name_plural': 'PushSubscriptions',
                'db_table': 'pushsubscription',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('medico', models.CharField(blank=True, max_length=255, null=True)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='restfull.paciente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'agendamento',
                'ordering': ['data'],
                'indexes': [models.Index(fields=['data'], name='agendamento_data_e15a6e_idx'), models.Index(fields=['paciente'], name='agendamento_id_paci_89e19f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usuario_email_0240ec_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['id_paciente'], name='usuario_id_paci_bbcc75_idx'),
        ),
    ]
