# Generated by Django 5.2.8 on 2026-05-05 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id_responsavel', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_paciente',
        ),
        migrations.RemoveIndex(
            model_name='agendamento',
            name='agendamento_id_paci_89e19f_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuario_id_paci_bbcc75_idx',
        ),
        migrations.RenameField(
            model_name='pushsubscription',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='id_paciente',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='restfull.usuario'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='restfull.usuario'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['usuario'], name='agendamento_id_usua_ba082d_idx'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='responsavel',
            field=models.ForeignKey(blank=True, db_column='id_responsavel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='restfull.responsavel'),
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
