# Generated by Django 5.2.8 on 2026-05-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0002_responsavel_remove_agendamento_paciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ativar_notificacoes_graacc',
            new_name='ativar_notificacoes_agendinha',
        ),
    ]
