# Generated by Django 5.2.8 on 2026-02-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0005_alter_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
