# Generated by Django 5.2.8 on 2026-03-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restfull", "0007_remove_usuario_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacao",
            name="id_paciente",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
