# Generated by Django 5.2.8 on 2026-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restfull", "0009_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="auth",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="p256dh",
            field=models.CharField(max_length=500),
        ),
    ]
