# Generated by Django 5.2.8 on 2026-03-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restfull", "0011_alter_pushsubscription_auth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushsubscription",
            options={
                "verbose_name": "PushSubscription",
                "verbose_name_plural": "PushSubscriptions",
            },
        ),
        migrations.AlterModelTable(
            name="pushsubscription",
            table="pushsubscription",
        ),
    ]
