# Generated by Django 5.2.8 on 2026-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0012_alter_pushsubscription_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='mensagem',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
