# Generated by Django 5.2.8 on 2026-03-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0015_usuario_notificacoes_usuario_timeout_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='notificacoes',
            new_name='ativar_notificacoes',
        ),
    ]
