# Generated by Django 5.2.8 on 2025-12-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='lembrete_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='medico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
