# Generated by Django 5.2.8 on 2026-04-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0002_agendamento_lembrete_enviado_agendamento_medico_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuario_id_paci_bbcc75_idx',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_paciente',
        ),
        migrations.AddField(
            model_name='usuario',
            name='paciente',
            field=models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='restfull.paciente'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['paciente'], name='usuario_id_paci_bbcc75_idx'),
        ),
    ]
