# Generated by Django 5.2.8 on 2026-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0002_agendamento_lembrete_enviado_agendamento_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
