# Generated by Django 5.2.8 on 2026-02-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0003_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modo_google',
            field=models.BooleanField(default=False),
        ),
    ]
