# Generated by Django 5.2.8 on 2026-02-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0004_usuario_modo_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
