# Generated by Django 5.2.8 on 2026-02-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0006_usuario_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
    ]
