# Generated by Django 5.2.8 on 2026-03-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restfull", "0008_notificacao_id_paciente"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_usuario", models.BigIntegerField()),
                ("endpoint", models.URLField()),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
            ],
        ),
    ]
