# Generated by Django 5.2.8 on 2026-03-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restfull", "0010_alter_pushsubscription_auth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="auth",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="endpoint",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="p256dh",
            field=models.CharField(max_length=255),
        ),
    ]
