# Generated by Django 5.2.8 on 2026-03-13 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0013_rename_mensagem_notificacao_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restfull.usuario'),
        ),
    ]
