# Generated by Django 5.2.8 on 2026-03-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0014_alter_pushsubscription_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificacoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='timeout_seconds',
            field=models.BigIntegerField(blank=True, default=10000),
        ),
    ]
