# Generated by Django 5.2.8 on 2026-03-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0016_rename_notificacoes_usuario_ativar_notificacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='restfull.usuario'),
        ),
    ]
