# Generated by Django 5.2.8 on 2026-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0017_alter_pushsubscription_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ativar_notificacoes',
            new_name='ativar_notificacoes_consultas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ativar_notificacoes_graacc',
            field=models.BooleanField(default=True),
        ),
    ]
